experiment:
    id: fusion_test_v1

##Data
data:
    data_dir: '/media/fang/extra/dataset/data_odometry'
    resolution: 0.1
    dataloader: 'KITTI'
    split: 'train'
    train: [ '00', '01', '02', '03', '04', '05', '06', '07', '09', '10' ]
    validation: [ '08' ]
    test: ['11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21']
    num_points: 10000
    max_range: 50.
    dataset_norm: False
    std_axis_norm: False

##Training
train:
    uncond_prob: 0.1
    uncond_w: 6.
    n_gpus: 1
    num_workers: 4
    max_epoch: 35
    lr: 0.0001
    batch_size: 1
    decay_lr: 1.0e-4

diff:
    beta_start: 3.5e-5
    beta_end: 0.007
    beta_func: 'linear'
    t_steps: 1000
    s_steps: 50
    reg_weight: 5.0

##Network
model:
    out_dim: 96
    use_fusion: True # Enable Gated Attention Fusion
